hash-format = "sha256"

[[files]]
file = "config/ftbbackups2.json"
hash = "658cdfc3d5b6794b28c8fc84fa1c91daa352017ae1145a006c99060f2be13cde"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "c22ebc9646c063a5c53acae5b49a0b54f8b21500ecc79a9c52b142775512b2d6"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "832691489ab19e2f0a4b81b77c143a8dceb5f3f395cdee96bcddd893fb01b363"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "220695895a8fd68ca82b7b3c34d8499b4f6ea73f6588e3dfbccd2307af0b924d"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "ab608dc348e5a47bc1005c04925140942feeb2519f5ed6a9b01be74da790835b"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "1999e2e85cc30a463ba4bb84ab2f612d8f55e68acc27279abad1ada8306fbd9e"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "6dee7917c9156b4281bec000688abfa299a11e118fba9817966832e02f148d68"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "403901ef07216a3f4a0d1e70dc02d1c0c41893e9f28f73017f11bc30884826bf"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
hash = "1edd2cfabb619660184561ab311bf5a6ad8d49d950030de1fef3cae4f9a549dd"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "b1da0afe23273616b36e2c6d815819ea43ff3847db20639067cfa8e13e930753"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a216e613b5ada8a83972394c8b52331388f6d3e41187a04c3bced3f1752bea70"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "86280b5ea045ad198494bfc49641dd803010e35069c957a4d4390fd276cbe0c7"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "a86751e4931b83d8f3de8e84e38f2dc0aa316e40c99b9e9f03a9276659a474b6"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "ba3fce3844b6383543275c04ba0811d09cade4eb8471de9764ead2989e1dfbf1"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "63ce3cead9fe9a025516f0fd5bc972c24f3586fd3156b331e9e95af81e146a4b"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "7ade9694388d80def1aba6b3653a1a0ea8a68eb14a42e2bffd076fd1335a5ce8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "dff937930734d00e3cd2c644d20d5015df3ad53cc9d23fae2704326774cadbad"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6a2b381b6a18c0b74dbc04a25cc8266964c3a5535885caa0dc5fa6c213fc8855"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fast-async-world-save-forge-fabric.pw.toml"
hash = "b37dab22331ef3cd0688102a17689235f12c195725463125d5cedddbe37248fe"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "c9babfbb0db58f9edfc38666af8ef4ce24fe0cd0594d3c421bb51410fb6c3fa2"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "36d3f5054974aa0abfd8edb01d7b99d41497c90559e52485dbc0d1e420f4bba0"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
hash = "6cfb1afb313f18d7cfe584ab972c8e183ade60083e256f4c1f70d0248190416a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "bc4f9441d69eefd3d48ed921338fbad1d24d0ecc671f755a83de0ad9f6418d3c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "603e4d77cd5ee641515822d3319bf86b09f03671628e705cdf2f93af95f9214f"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "e13086d01de1728d52ff0e0d2f460866855b0c325611f6c655d3a7801d851782"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "8d40436970d9adcfe3c0b72c9f0cd1af217948469b091b0f07ca3df187ce2e61"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e5506cea71f62e147a45e6c72a55a430fce5937024f648c819c15dc14b500462"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e26dacab5ed497b7bf6500e389eba5e21cd4b9d7b38089045cd26818a4d2f589"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "0f66adb84216f6411f87aa060a55b0613c2c5687f667c5b0de4971604dd49520"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "78d3414d086eeffc1e271cc189ea7a33d1dc2ed6f570f39e4abe4b33fc0acc58"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "87c4d42219d3aea70af7aa016e0e4bdfac94d2a4ece9e719e8e84e9203735300"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "be165c98a6b6878a158d7d0606f68bf2c8e59cde8b95455d4b872c82f0041fc8"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6eea5e1db3dbca126b82f211bf0d2fcf2cf13097023fdef3dd668e48581a73d0"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "d122f53efcfd54e24ef7e15247bbebe788d4ea475c2f5b84ccc1254dc625a1ec"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "67d7d0cd20e2933d7b2a305d60e109bc6db868883209416ccfe5e22de281c1da"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "18360f497689d81ce5b4a58571c099bf5a7f66e085ccd7196cd129158b328f15"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "4ed5bf9e808739ddeec2692fbd7c16b3df653f1b2823de3f07e5dced1c5fc439"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "0993352e081593fca386a8a4e6473ece541a27e018c8384239f27f79d73133a0"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a04338ef93757875028cc1f2f7287199b3e7024c906af6ee53437d8c8a7f9f06"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "0ebcac819db1ea71488bc30ee57ab0c7f65b6e9395890f52120d8700cacc6286"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "0bdb14d12c298ab3a115ba719c6a6ee294bcfb97ed12efe53dd1ef753efc82d4"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "214c50c94d7484fe1c4522f3b14f3e5528b68760f3e48293a87f3ccf6ca733f7"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "4491e4d814b8780c9286070c621ebb4ad93d159d31d48830cd8bcca0cff87e40"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "40630d6f1fdd0011a3aa9270af99b331103a9eaed6e7832650e85b325a50bc85"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "2d27a6e7c7e28a33b4e3d85106f80fd6629f060ec31a8be525f1c2ac9f769cf1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "3ef916454266cdbcbd3f517c53b1e27b360caa5266bf1b44d0d627aeab643516"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "a6948eb25808d55a8dc3b9a64999181ebae738c3679ced2981c7c1ec34b9b0b6"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "305e286ce8213886bb80d026451f1695cfd681d4f5d643bba3933b3e1120a998"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "529e78bd1891441addb1500852b01b934500d14dbd5c8362dba1f172db0ba181"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "d30c99840d3ecd0b1ca1a4023e3b956c781ad06a3b44705e5494d04a31c9abf3"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ea0eb6ab539b43926503901694913866aa81a9a644cd3469080214a7ca785db2"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "59e45ade7176229ff9750ae85356ba4a92b5124592dd09b0244c861cfda08575"
metafile = true

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.5.1.zip.txt"
hash = "7aa8b1938cea04af88f7a49e5dd372bb9b3cb46d5e73b0a602b20c1014d44616"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "3add1378e964947556ec43ebc86a431981cfa67c9b95353105d7f48deb58ff3d"
metafile = true

[[files]]
file = "shaderpacks/solas-shader.pw.toml"
hash = "ee7d85e560722638174288e87de2c5e8ae82c8242de6614745e52d82acf7700c"
metafile = true
