hash-format = "sha256"

[[files]]
file = "config/ftbbackups2.json"
hash = "658cdfc3d5b6794b28c8fc84fa1c91daa352017ae1145a006c99060f2be13cde"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1502d3ac2c2ce4d3dc4c2db6ca6e95fb2a5d4a279e6e1413f6c427be222887a0"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "f8805d3902fb3e31ea9e53f684e3d731b5ac7d2fd2507c475fd1f5f4da266a2f"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "492b3c59c096542b5ca733e5a19f66c870deaa6a98a409ee8497fe50d39ac7db"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "36a24bed3fd2d7a2f31dbf2543e437ff200dfc80e48b59d5ca77c66562211720"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "6088be62ff0bc4e93388ba995418a376a1b7dfd062cce84bc36349b34ffa4af6"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "4ee1808a7fb319d469dece5752cedb05dacb9afbe48021fa664f54b8c83fdc45"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "c6214a3903e034a911d984f84a98ad04fd7a0f76431d16986458ceb782b7d8c1"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
hash = "1edd2cfabb619660184561ab311bf5a6ad8d49d950030de1fef3cae4f9a549dd"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "7243f5258960ac15593488a49811b27f6de0e5fce447768e4588fcff95abc757"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "b98e0aca52ce8d08ee8df7177886589511b8bca779af078a6ff4837e814bccf4"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b152c75412428e5f53667cb0836fa1323ca93cbd925e456239710a2e261d9963"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "da925d1159906a6c993fa4be167a48ae350d77daa1950a68135bf56c4e0dbb62"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "f67b2da196e96f6a086b8c60d3f1d4b18c1c54d65056c003723fa22213bb4678"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3a96a1e5bef30c16a8738c2a8acf54693225122424c39fa06f589a11ccc83b90"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "b6dd8c2e3c0b386b2551844c81c41940554f373c24aa8a35f20dfd63022e59fb"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0345fbfa8542b5ec84535fe2aff0f5cc4e801ecc337f926d4e2310b53f458569"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fast-async-world-save-forge-fabric.pw.toml"
hash = "b37dab22331ef3cd0688102a17689235f12c195725463125d5cedddbe37248fe"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "65aaaca6973786baf12f943cb700deac5d9dee8a4813ec1368773c35653b18f8"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d74f72f3bf13c4ef7d60b6e2defecd3c7af77ed9be7764cf1ed10ea1fd707a1f"
metafile = true

[[files]]
file = "mods/ftb-backups-2.pw.toml"
hash = "6cfb1afb313f18d7cfe584ab972c8e183ade60083e256f4c1f70d0248190416a"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "6e6bd7a9eee2f733202beecd7ceecf8248542f3e043849ae954e928058927f35"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "77364cc74f5c0819ef77e5e2fd11bd304ad98dc193348d3d875e23fae62f8f74"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "4da23b529e31714ab48cba4e292a9430fecd61d3fcda09b0e8dc76b34cb049dd"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "fecd2e19a6afd8109bb6cfc281d158e3f7a5d6646a99340e2ece5d1aaece4edc"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "83fc77051e675c101fddb28ed303ce57deb4d26b58c025d4d9f60b2d1b37a5c1"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "c0db6f1d3a53a5c025618ce1862119caa569329dabe3674ff9beb05115f56302"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "9946fd3c2a85099bb68cff8a2168601c3f1c7879fc42d018171c7cf5f25693d2"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "9901b4a332af2554d61e1a0547a8d6dce114232ecc48f5b4512ab867c1d680ef"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "802981efce132e93b99352dacae410bf7b3e356f2e9de14b0ff9cea0beb31bb9"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "204a4b3b041fad4bb4dc543c74d540fcf239710494d2130cebe700bf1d8a7805"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "dc24a4cc0ad484d6593997c197ea602fac4d98c45dab0de6421e704c3851acd9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "bedbd2675abf6bdb06c80570ba63d88e08caf7bb431d01e446d8770a5c62a9fb"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "5ae220cfbb26641c68740ad0166c78f353680886fc28087e63bf07280a47ddbb"
metafile = true

[[files]]
file = "mods/servux.pw.toml"
hash = "af842a44a80264384c518764091621542eee6abe65fa368b13e1926c6a88c07a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "69786785c676fc55890792c5906fa360b34a89dd76d072eec30294b49155c00d"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "2d27a6e7c7e28a33b4e3d85106f80fd6629f060ec31a8be525f1c2ac9f769cf1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "22cff4ede67e4810127dfb952db897559bf64b000697dc78bf6b2b25eaedfb5c"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "a7d0bbc50957cfb31069dc6ae4ede843f64fa40a34613986bc7adbb856ffb71d"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "121b4fa5f12aef9a36418922a8be02aa715ad40347165e31dcdf293f16019519"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e71ac6769675de1d2338a13e116f2aefcc8965ab0bc18b75a53572531c1447dd"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "22052f42b1b73226d9508ef42af962471c79c7daa281aac66a82a90c7d7bb9e5"
metafile = true

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.6.1.zip.txt"
hash = "7aa8b1938cea04af88f7a49e5dd372bb9b3cb46d5e73b0a602b20c1014d44616"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/solas-shader.pw.toml"
hash = "aed8da05c8e4d9c7b68e82e8d9432b88769f7c4eeb8bd735845a189ef0e2bbf9"
metafile = true
