name = "vanilla-world"
author = "harkin"
version = "0.0.1"
description = "Mostly vanilla Fabric server pack, designed to improve performance primarily and disable some really annoying MC parts. Some extra structure generation is added to spice up the water"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e7e8bd18a1115817be7d384f04ecacf271f9ec795197653a86619f30367cbc8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
