name = "vanilla-world"
author = "harkin"
version = "0.0.1"
description = "Mostly vanilla Fabric server pack, designed to improve performance primarily and disable some really annoying MC parts. Some extra structure generation is added to spice up the water"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88625501645f7bc893ed9d12c0e66235af8ef5f2314f6559e056a1f55a123d16"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
