name = "vanilla-world"
author = "harkin"
version = "0.0.1"
description = "Mostly vanilla Fabric server pack, designed to improve performance primarily and disable some really annoying MC parts. Some extra structure generation is added to spice up the water"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0abe41f5377029a3f21a23fdbb485b90a00d491ef7a866324eadc27fe6ca085b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"
