name = "skyblock-carpet"
author = "harkin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffe4487f8de0e3073d9a62572308912c9e72667e10314abf7fea94116f043e94"

[versions]
fabric = "0.16.14"
minecraft = "1.20.4"
